image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
tasks:
  - init: npm install
    command: npm run server 3000
  - command: gp await-port 3000 && gp preview $(gp url 3000)

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.5.0:MOFjKFx34CxWS0nqmAG75g==
    - haskell.haskell@1.1.0:Wt1BvkxTWaeCQD86YIN0fw==
    - hashicorp.terraform@2.2.3:bBQoMVR7TCwCZWURotrh3w==