epple2 (Emulated Apple ][)
==========================
Christopher A. Mosher <cmosher01@gmail.com>

image:https://travis-ci.org/cmosher01/Epple-II.svg?branch=master["Build Status", link="https://travis-ci.org/cmosher01/Epple-II"]

Home page: http://mosher.mine.nu/epple2[]

+epple2+ is an emulator of the *Apple ][* and *Apple ][ plus*
computers from Apple, Inc. It strives to faithfully simulate
much of the internal workings of the original Apple ][,
including the individual cycles of the 6502 CPU, and the
NTSC video signal generation, including the ``strange orange
line'', other color anomalies, and the ``floating data bus.''
_Understanding the Apple ][_, by Jim Sather, is the primary
source for information about the internals of the Apple ][.

The CPU and video timings are synchronized, and the emulator
is designed to run at the same speed as the original
machine (if your computer is fast enough). It also emulates
several different types of television screens and monitors
for the display.

It includes emulation of a Disk ][ controller card, a ROM
firmware card, and a RAM Language card, as well as a
simple clock card.

+epple2+ is written in C++, and is designed to be buildable
on Linux (gcc) or Windows (mingw). http://www.libsdl.org/[SDL]
is the only dependency.

+epple2+ is released under GPLv3.

See files +COPYING.*+ for copyright notices.
