=== Display

The orignal Apple ][s didn't come with a display. The user needed to use either a standard
television, or a monitor, to see the computer's output. The EPPLE ][ emulates a variety of
displays; you can cycle between the different types using +F2+.
There are two major types of displays: televisions and monitors. Monitors generally have
higher quality (sharper) displays. The displays show the normal visible area of the NTSC
video signal generated by the emulated Apple ][ machine.

==== Monitors

The emulator provides a color monitor, and three monochrome monitors (white, green, and orange).
These emulate standard, no-frills NTSC monitors. The most noticeable characteristic of monitors
is the horizontal display of pixels. Monitors react faster than TVs, so two adjacent pixels will
not merge together; both will be distinctly visible, with blackness between them. For example,
type in the following Applesoft command, then cycle through the display types. The monitors
will show thin, vertical, green lines; TVs will show continuous horizontal lines.

--------
GR : COLOR=4 : HLIN 10,20 AT 10
--------

==== Televisions

There are two types of television displays, referred to as ``old'' and ``new.'' Each has color and
monochrome (commonly known as ``black and white'') varieties. Televisions react more slowly to
changes in the incoming video signal than monitors do, and as a result, horizontal pixels will
merge together, forming a more uniform appearance. The ``new'' color TV display uses the pre-defined
color pallette (described below under ``Colors''), and the black and white TV uses the same
pallette, but fully desaturated. The ``old'' color TV is the most interesting. It emulates the
signal decoding circuitry of a real television. This includes separating out the ``chroma'' portion
of the incoming NTSC video signal using a filter algorithm, and _calculating_ the color to display.
It does not use the pre-defined colors.

[NOTE]
This mode is very CPU intensive, so your computer (that is, the one that EPPLE ][ is running on)
may not be able to run fast enough to run at the speed of the original Apple ][. The Apple ][ CPU
runs at about 1 MHz, but the video generator runs at 14 MHz; so the inner-most loop in the
EPPLE ][ must run 14 million times per second to keep up.

==== Colors

The color palatte used for the
color monitor and new color TV is pre-defined, and was determined through observation of a real
Apple ][ machine on a standard TV, the colors being matched by eye. The old color TV, however,
uses _algorithms_ to calculate the colors it displays.

==== Scan Lines

NTSC displays (TVs or monitors) usually receive signals that are interlaced. However, the
Apple ][ doesn't generate interlaced screens. This causes blank rows between each displayed
row of pixels. The EPPLE ][ emulates this behavior, but also allows you to ``fill in'' these
black rows with a copy of the row above it, for a more continuous display (vertically). Use
the F4 key to toggle between these two modes.

==== Resolution

The Apple ][s are commonly documented as having a resolution of 280x192 pixels, and to an
extent this is true. Vertically there are 192 pixels, but since there is no interlacing,
it is more accurate to display them with one blank space between each. So the EPPLE ][ has
two times 192, or 384, vertical pixels in its display. Horizontally there are 280 pixels, but
each could also be shifted right one-half dot, allowing for two times 280, or 560, different
horizontal displayable positions. To emulate this, the EPPLE ][ shows each emulated pixel as
two pixels wide, and displays an emulated half-dot shift as an actual one pixel shift. So the
display area of the EPPLE ][ is 560x384. There is an informational area below and to the
right of the emulated display that shows various statistics of the emulator. So the total screen
area used by the EPPLE ][ is a standard 640x480 pixels.

==== Full Screen

The EPPLE ][ can run in either full-screen mode, or within a window. Use the +F3+ key to toggle
between the two.

==== Informational Area

The area at the bottom and the right of the EPPLE ][ display show various information about
the emulator.

* POWER light
* current cards in SLOTS
* CASSETTE tape information
* emulated CPU speed (MHz)
* function-keys help
