== Download

[TIP]
Usable Apple ROMs (proprietary
footnoteref:[disclaimer,You must
respect the fact that the Apple
System Software and
Apple Disk Operating System (DOS) Software are
_proprietary_ software; they are copyright by Apple and/or others. This web page is not
providing any advice as to the legality of any copying or downloading you may perform.
])
are available at the http://mosher.mine.nu/apple2/[Apple II Library].

The following software is licensed under
http://www.gnu.org/licenses/gpl-3.0-standalone.html[GPLv3].

Epple ][ Program: http://mosher.mine.nu/epple2/download/epple2-latest.tar.gz[epple2.tar.gz]

System ROM (Demo): http://mosher.mine.nu/epple2/download/epple2sys-latest.tar.gz[epple2sys.tar.gz]

Card ROMs (stdin/stdout/clock): http://mosher.mine.nu/epple2/download/epple2cards-latest.tar.gz[epple2cards.tar.gz]

See <<_building_from_source,Building>> to build from sources.



== What To Download

=== Epple ][ Program&mdash;The Hardware (Emulated)

The _Epple ][ Program_ package is the emulator itself, which emulates the
Apple ][ or Apple ][ plus _hardware_, as well as the
<<cards,peripheral card>> hardware. This is the main program, so you will
certainly need to download this package. To have a full functioning emulator,
you will also need System ROMs and Card ROMs, as described in the following
sections.

[[firmware]]
=== System ROMs&mdash;The Main System Firmware (Demo or Real)

Since the Epple ][ program emulates only the hardware, you will also need to download some _system software_
for it to run. This is commonly called ``firmware'' or ``ROMs,'' because it is stored in the
read-only memory area of the emulated system. The original system software on the
Apple ][ machines is copyright by Apple, and is proprietary. If you own an actual
Apple ][ or Apple ][ plus machine, you can copy footnoteref:[disclaimer] the firmware
from it ($D000-$FFFF) (into a file on your PC) and use it. Alternatively, you can
download footnoteref:[disclaimer] the firmware images from the http://mosher.mine.nu/apple2/[Apple II Library].

If you do not want to download the proprietary firmware, you can still use the emulator (albeit
in a restricted manner) with the free (GPLv3) _System ROM (Demo)_ package. Download
the file for your platform and
install as appropriate. You can choose either binary format (ready to run), or source if you want
to assemble it yourself (using the http://www.floodgap.com/retrotech/xa/[xa Assembler]).
The Demo System ROM only provides commands to dump or set memory bytes,
or run a program in memory. It is not compatible with any Apple software, nor can it read from disks.
It's just a free simple demo system to make the emulator do something reasonable.

=== Card ROMs&mdash;The Peripheral Card Firmware

If you are going to use the Disk ][ Controller peripheral card (which you almost certainly will, if
you want to read any floppy disk images), you will need to have to original ROMs from Apple.
No demo of the Disk ROMs are provided here; you will need to
use the original ROMs, which can be obtained from an original machine (by copying footnoteref:[disclaimer]
it from $C600-$C6FF into a file on the PC), or by downloading footnoteref:[disclaimer] it
from the http://mosher.mine.nu/apple2/[Apple II Library].
(And, of course, you will need the real Apple System ROM, as noted in the previous section,
not the Demo System ROM.)

If you are using any of the clock, the standard output, or the
standard input <<cards,peripheral cards>>, you will need to download their firmware as well,
which are contained in the _Card ROMs_ package. You can choose either binary format
(ready to run) or source format (to assemble it yourself(using the
http://www.floodgap.com/retrotech/xa/[xa Assembler]).
If you are _not_ going to use the stdin, stdout, or clock
cards, then you do not need to download this package.
