---
on:
  push:
    branches:
      - "master"

jobs:
  "build-roms":
    runs-on: "ubuntu-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          sudo apt-get update -qqqq
          sudo apt-get upgrade -qqqq
          sudo apt-get install -qqqq xa65

      - uses: "actions/checkout@v3"

      - name: "Build artifacts"
        run: |
          set -x
          cd rom
          make
          ls -l *.a65

      - uses: "actions/upload-artifact@v3"
        with:
          name: "epple2-roms"
          path: "./rom/*.a65"
