---
on:
  push:
    branches:
      - "master"

jobs:
  "build-roms":
    runs-on: "ubuntu-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          sudo apt-get update -qqqq
          sudo apt-get upgrade -qqqq
          sudo apt-get install -qqqq xa65
          m4 --version
          xa --version
          ldo65 --version
          reloc65 --version

      - uses: "actions/checkout@v3"

      - name: "Build artifacts"
        run: |
          set -x
          cd rom
          make
          ls -l *.a65

      - uses: "actions/upload-artifact@v3"
        with:
          name: "epple2-roms"
          path: "./rom/*.a65"



  "build-epple2-ubuntu":
    runs-on: "ubuntu-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          sudo apt-get update -qqqq
          sudo apt-get upgrade -qqqq
          sudo apt-get install -qqqq libsdl2-dev

      - uses: "actions/checkout@v3"

      - name: "Build"
        run: |
          set -x
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ls -l src conf
          cat conf/epple2.a2ploaded.conf



  "build-epple2-macos":
    runs-on: "macos-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2

      - uses: "actions/checkout@v3"

      - name: "Build"
        run: |
          set -x
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ls -l src conf
          cat conf/epple2.a2ploaded.conf



  "build-epple2-windows":
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Download SDL2 package"
        run: >-
          wget
            "https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-devel-2.24.2-VC.zip"
            -outfile "C:/Program Files/SDL2-devel-VC.zip"

      - name: "Install SDL2"
        run: >-
          Expand-Archive
            -LiteralPath "C:/Program Files/SDL2-devel-VC.zip"

      - name: "Build"
        shell: "bash"
        run: |
          set -x
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ls -l src conf
          cat conf/epple2.a2ploaded.conf
