---
on:
  push:
    branches:
      - "master"

jobs:
  "build-roms":
    runs-on: "ubuntu-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          sudo apt-get update -qqqq
          sudo apt-get upgrade -qqqq
          sudo apt-get install -qqqq xa65
          m4 --version
          xa --version
          ldo65 --version
          reloc65 --version

      - uses: "actions/checkout@v3"

      - name: "Build artifacts"
        run: |
          set -x
          cd rom
          make
          ls -l *.a65

      - uses: "actions/upload-artifact@v3"
        with:
          name: "epple2-roms"
          path: "./rom/*.a65"



  "build-epple2-ubuntu":
    runs-on: "ubuntu-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          sudo apt-get update -qqqq
          sudo apt-get upgrade -qqqq
          sudo apt-get install -qqqq libsdl2-dev

      - uses: "actions/checkout@v3"

      - name: "Build"
        run: |
          set -x
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ls -l src conf
          cat conf/epple2.a2ploaded.conf



  "build-epple2-macos":
    runs-on: "macos-latest"
    steps:
      - name: "Prepare runner"
        run: |
          set -x
          HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2

      - uses: "actions/checkout@v3"

      - name: "Build"
        run: |
          set -x
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ls -l src conf
          cat conf/epple2.a2ploaded.conf



  "build-epple2-windows":
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up vcpkg and install dependencies"
        # TODO use https://github.com/lukka/CppCMakeVcpkgTemplate instead of this
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          vcpkg install sdl2

      - name: "Build"
        shell: "bash"
        run: |
          mkdir build
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_PREFIX_PATH=vcpkg/installed/x64-linux
          cmake --build build
          dir build/src
          dir -Path build/conf
          cat build/conf/epple2.a2ploaded.conf
