---
on:
  push:
    tags:
      - "*"

env:
  name: "epple2"
  desc: "Apple ][ emulator"
  deb_depends: "libSDL2"

permissions:
  contents: "write"

jobs:
  "publish":
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - run: |
          set -x
          sudo apt-get update -qqq
          sudo apt-get upgrade -qqq
          sudo apt-get install -qqq xa65 libsdl2-dev
          ./bootstrap
          ./configure
          make

      - run: |
          mkdir -p ./deb/usr/local/bin
          cp ./src/epple2 ./deb/usr/local/bin/
          mkdir -p ./deb/usr/local/etc/epple2
          cp ./conf/epple2.conf ./deb/usr/local/etc/epple2/
          mkdir -p ./deb/usr/local/lib/epple2/system
          cp ./rom/epple2sys.a65 ./deb/usr/local/lib/epple2/system/
          mkdir -p ./deb/usr/local/lib/epple2/cards
          cp ./rom/stdout.a65 ./deb/usr/local/lib/epple2/cards/
          cp ./rom/stdin.a65 ./deb/usr/local/lib/epple2/cards/
          cp ./rom/clock.a65 ./deb/usr/local/lib/epple2/cards/

      - uses: "jiro4989/build-deb-action@v2"
        with:
          package: "${{ env.name }}"
          desc: "${{ env.desc }}"
          maintainer: "${{ github.repository_owner }}"
          version: "${{ github.ref }}"
          arch: "amd64"
          package_root: "./deb/"
          depends: "${{ env.deb_depends }}"

      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            *.deb
